export const DontationText =
  "DONATIONS NOT ACCEPTED FROM STATE(S) CHARITY NOT REGISTERED. STATE REGISTRATION DOES NOT CONSTITUTE, OR IMPLY ENDORSEMENT, APPROVAL, OR RECOMMENDATION BY A STATE. SEEDFORME DOES NOT VERIFY WHETHER OR NOT A CHARITY ON IT’S PLATFORM IS REGISTERED, OR COMPLIANT WITH STATE(S) REGISTRATION OR THE IRS. CONTRIBUTIONS MAY BE TAX-DEDUCTIBLE PURSUANT TO THE PROVISIONS OF SEC. 170(C) OF THE INTERNAL REVENUE CODE OF 1986, 26 U.S.C. §170(C)";
export const BASE_URL = "https://seedapis.seedforme.com/uploads/";


